### PR TITLE
Fix unicycler tool for unicycler 0.2.0 bioconda package.

### PR DESCRIPTION
**Pull request by jmchilton**
Ping @bgruening @nekrut 

The pilon trick and the no_long option seem to work for me with the bioconda Unicycler. Maybe you are using a dev version that is different than 0.2.0 for testing?

With this PR this wrapper essentially works semantically with unicycler that is on bioconda and the first test passes, but the second test fails at the minimap step - a machine instruction fault. Here is a log of that second test case - https://gist.github.com/jmchilton/b411b695170c1daea6589f5d76e326cb - I get essentially the same thing whether running it directly or using the tool wrapper via Planemo.

Any clue based on that log if that is a problem with this version of unicycler or with the bioconda packages? My next step would be to install unicycler outside of Conda and see if I can reproduce that problem.

### CODE REVIEW

**Comment by nekrut** [comment]
For testing I was using unicycler outside conda. The unicycler has been updated recently, so perhaps we need to update the conda package, no?

**Comment by bgruening** [comment]
Try the conda version `0.3.0b`.

**Comment by nekrut** [comment]
@bgruening: I do not see `0.3.0b` in bioconda though

**Comment by martenson** [comment]
@bgruening @nekrut https://bioconda.github.io/recipes.html and https://anaconda.org/bioconda/unicycler are giving different results :/ version 0.3.0b is in the latter...

**Pull request merged**
